### ISSUE TITLE
dart sdk version error

### ISSUE THREAD

**Issue by moda20** [kalismeras61/flutter_wallet_ui#1]
hey I just run `flutter packages get` and  I got this error   : 

```

The current Dart SDK version is 2.1.0-dev.9.4.flutter-f9ebf21297.

Because flutter_wallet_ui_challenge requires SDK version >=2.1.0 <3.0.0, version solving failed.
 
pub get failed (1)

```

is the exact version of dart very useful  ? can't we have  any version like the dev version I have ?

**Comment by kalismeras61** [comment]
I am using master channel which is the required latest version of Flutter. I will change it with stable version

**Comment by kalismeras61** [comment]
Upgrade your flutter version v1.2.1
