### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by kitlu007** [kalismeras61/flutter_wallet_ui#3]
Hello There,

The license seems to be missing. Can we use the ui for commercial use though?

**Comment by kalismeras61** [comment]
Yes, you can use it.

**Comment by fatihky** [comment]
Selamlar. Lisans dosyası bulunmadığında serbestçe kullanmak pek mümkün değilmiş anladığım kadarıyla. Şuraya bakabilirsiniz: https://opensource.stackexchange.com/a/1721
Burada verdiğiniz iznin hukuki karşılığını bilmiyorum ama tavsiyem, eğer sizin için de uygunsa, açık kaynak lisanslarından birisi ile projeyi lisanslayarak bu izni sağlamanız olur.
